// Auto-generated from Door_Specs.xlsx (WoodLand's supplier master packing list).
// 64 unique products, deduplicated by item code. Each product links to its own
// page at /products/[slug] — these pages are intentionally NOT in the site nav;
// they're only reached by clicking a product card on /collections or the homepage.

export type ProductCategory = "pet" | "pph" | "ccp";

export interface Product {
  slug: string;
  code: string;
  category: ProductCategory;
  materialShort: string;
  materialLong: string;
  size: string;
  nw: string;
  features: string[];
  image: string;
  images?: string[];
}
export const products: Product[] = [
 {
  slug: "26p1-10-lb205",
  code: "26P1-10-LB205",
  category: "pet",
  materialShort: "PET",
  materialLong: "Polyethylene Terephthalate",
  size: "900×2100mm",
  nw: "50kg",
  features: [
    "100% Water Resistant",
    "Scratch Resistant Surface",
    "Termite Proof",
    "No Polish or Paint Required",
    "Warp & Weather Resistant"
  ],
  image: "/products/26p1-10-lb205.jpg",
  images: [
    "/3.jpeg",
    "/lock.png",
    "/design.png",
    "/hinge.jpg",
    "/hinge.jpg"
  ],
},
 {
    slug: "lb2601-15-122",
    code: "LB2601-15-122",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-122.jpg",
  },
   {
    slug: "zf-6813",
    code: "ZF-6813",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6813.jpg",
  },
  {
    slug: "26p1-10-lb206",
    code: "26P1-10-LB206",
    category: "pet",
    materialShort: "PET",
    materialLong: "Polyethylene Terephthalate",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26p1-10-lb206.jpg",
  },
  {
    slug: "26p1-10-lb207",
    code: "26P1-10-LB207",
    category: "pet",
    materialShort: "PET",
    materialLong: "Polyethylene Terephthalate",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26p1-10-lb207.jpg",
  },
  {
    slug: "26p1-10-lb208",
    code: "26P1-10-LB208",
    category: "pet",
    materialShort: "PET",
    materialLong: "Polyethylene Terephthalate",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26p1-10-lb208.jpg",
  },
  {
    slug: "26p1-10-lb209",
    code: "26P1-10-LB209",
    category: "pet",
    materialShort: "PET",
    materialLong: "Polyethylene Terephthalate",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26p1-10-lb209.jpg",
  },
 
  {
    slug: "lb2601-15-123",
    code: "LB2601-15-123",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-123.jpg",
  },
  {
    slug: "lb2601-15-124",
    code: "LB2601-15-124",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-124.jpg",
  },
  {
    slug: "26h1-13-lb310",
    code: "26H1-13-LB310",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26h1-13-lb310.jpg",
  },
  {
    slug: "26h1-13-lb311",
    code: "26H1-13-LB311",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26h1-13-lb311.jpg",
  },
  {
    slug: "26h1-13-lb312",
    code: "26H1-13-LB312",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26h1-13-lb312.jpg",
  },
  {
    slug: "lb2601-15-125",
    code: "LB2601-15-125",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-125.jpg",
  },
  {
    slug: "lb2601-15-126",
    code: "LB2601-15-126",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-126.jpg",
  },
  {
    slug: "lb2601-15-131",
    code: "LB2601-15-131",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-131.jpg",
  },
  {
    slug: "26h1-13-lb313",
    code: "26H1-13-LB313",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26h1-13-lb313.jpg",
  },
  {
    slug: "lb2601-15-127",
    code: "LB2601-15-127",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-127.jpg",
  },
  {
    slug: "lb2601-15-128",
    code: "LB2601-15-128",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-128.jpg",
  },
  {
    slug: "lb2601-15-129",
    code: "LB2601-15-129",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-129.jpg",
  },
  {
    slug: "lb2601-15-130",
    code: "LB2601-15-130",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-130.jpg",
  },
  {
    slug: "26h1-13-lb314",
    code: "26H1-13-LB314",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26h1-13-lb314.jpg",
  },
  {
    slug: "26h1-13-lb315",
    code: "26H1-13-LB315",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26h1-13-lb315.jpg",
  },
  {
    slug: "26h1-13-lb316",
    code: "26H1-13-LB316",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26h1-13-lb316.jpg",
  },
  {
    slug: "lb2601-15-132",
    code: "LB2601-15-132",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-132.jpg",
  },
  {
    slug: "26h1-13-lb318",
    code: "26H1-13-LB318",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26h1-13-lb318.jpg",
  },
  {
    slug: "26h1-13-lb319",
    code: "26H1-13-LB319",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/26h1-13-lb319.jpg",
  },
  {
    slug: "lb2601-15-133",
    code: "LB2601-15-133",
    category: "pph",
    materialShort: "PPH",
    materialLong: "Polypropylene Homopolymer",
    size: "900×2100mm",
    nw: "50kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/lb2601-15-133.jpg",
  },
 
  {
    slug: "zf-6815",
    code: "ZF-6815",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6815.jpg",
  },
  {
    slug: "zf-6820",
    code: "ZF-6820",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6820.jpg",
  },
  {
    slug: "zf-6825",
    code: "ZF-6825",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6825.jpg",
  },
  {
    slug: "zf-005",
    code: "ZF-005",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-005.jpg",
  },
  {
    slug: "zf-006",
    code: "ZF-006",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-006.jpg",
  },
  {
    slug: "zf-009",
    code: "ZF-009",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-009.jpg",
  },
  {
    slug: "zf-010",
    code: "ZF-010",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-010.jpg",
  },
  {
    slug: "zf-015",
    code: "ZF-015",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-015.jpg",
  },
  {
    slug: "zf-6801",
    code: "ZF-6801",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6801.jpg",
  },
  {
    slug: "zf-6601",
    code: "ZF-6601",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6601.jpg",
  },
  {
    slug: "zf-6602",
    code: "ZF-6602",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6602.jpg",
  },
  {
    slug: "zf-6605",
    code: "ZF-6605",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6605.jpg",
  },
  {
    slug: "zf-6610",
    code: "ZF-6610",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6610.jpg",
  },
  {
    slug: "zf-6611",
    code: "ZF-6611",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6611.jpg",
  },
  {
    slug: "zf-7111",
    code: "ZF-7111",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-7111.jpg",
  },
  {
    slug: "zf-7001",
    code: "ZF-7001",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-7001.jpg",
  },
  {
    slug: "zf-7002",
    code: "ZF-7002",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-7002.jpg",
  },
  {
    slug: "f10",
    code: "F10",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/f10.jpg",
  },
  {
    slug: "ta611-830",
    code: "TA611-830",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/ta611-830.jpg",
  },
  {
    slug: "ta612-829",
    code: "TA612-829",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/ta612-829.jpg",
  },
  {
    slug: "ta927-829",
    code: "TA927-829",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/ta927-829.jpg",
  },
  {
    slug: "ta925-829",
    code: "TA925-829",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/ta925-829.jpg",
  },
  {
    slug: "zf-813",
    code: "ZF-813",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-813.jpg",
  },
  {
    slug: "zf-815",
    code: "ZF-815",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-815.jpg",
  },
  {
    slug: "zf-812",
    code: "ZF-812",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-812.jpg",
  },
  {
    slug: "zf-811",
    code: "ZF-811",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-811.jpg",
  },
  {
    slug: "zf-816",
    code: "ZF-816",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-816.jpg",
  },
  {
    slug: "zf-6003",
    code: "ZF-6003",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-6003.jpg",
  },
  {
    slug: "zf-820",
    code: "ZF-820",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-820.jpg",
  },
  {
    slug: "zf-821",
    code: "ZF-821",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-821.jpg",
  },
  {
    slug: "zf-822",
    code: "ZF-822",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-822.jpg",
  },
  {
    slug: "zf-825",
    code: "ZF-825",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-825.jpg",
  },
  {
    slug: "zf-829",
    code: "ZF-829",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-829.jpg",
  },
  {
    slug: "zf-828",
    code: "ZF-828",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-828.jpg",
  },
  {
    slug: "zf-836",
    code: "ZF-836",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-836.jpg",
  },
  {
    slug: "zf-807",
    code: "ZF-807",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-807.jpg",
  },
  {
    slug: "zf-806",
    code: "ZF-806",
    category: "ccp",
    materialShort: "CCP",
    materialLong: "Crystal Carbon Panel",
    size: "900×2100mm",
    nw: "45kg",
    features: ["100% Water Resistant", "Scratch Resistant Surface", "Termite Proof", "No Polish or Paint Required", "Warp & Weather Resistant"],
    image: "/products/zf-806.jpg",
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getRelatedProducts(product: Product, limit = 3): Product[] {
  return products
    .filter((p) => p.category === product.category && p.slug !== product.slug)
    .slice(0, limit);
}

/** Category-level info that doesn't vary per SKU — used on product pages
 * and the specs/performance table. Matches the Performance table shown
 * on the homepage. */
export const categoryInfo: Record<
  ProductCategory,
  { recommendedFor: string; scratchResistant: boolean }
> = {
  pet: { recommendedFor: "Bathrooms, kitchens & wet areas", scratchResistant: false },
  pph: { recommendedFor: "Bedrooms, living areas & everyday residential use", scratchResistant: true },
  ccp: { recommendedFor: "Premium interiors, villas & commercial spaces", scratchResistant: true },
};
